language: bash

sudo: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install lua5.1 luarocks
  
install:
  - sudo luarocks install lua-cjson

script:
  - bash tests/validate_site.sh
